{
 "title": "Cookie Sync",
 "time": { "from": "2024-05-12T14:55:44.495Z", "to": "2024-05-12T15:00:41.053Z" },
 "panels": [
  {
   "title": "Producer: queue length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "producer_exchange_queues_total_length",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer: failed to insert",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "consumer_storage_failed_to_insert",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP -> Streamer -> Consumer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(producer_handler_accepted[$__rate_interval])",
     "legendFormat": "Producer: accepted by HTTP"
    },
    {
     "expr": "rate(consumer_consumer_received[$__rate_interval])",
     "legendFormat": "Consumer: received by gRPC"
    },
    {
     "expr": "rate(producer_steamer_sent[$__rate_interval])",
     "legendFormat": "Producer: sent by gRPC"
    }
   ]
  },
  {
   "title": "Consumer: inserted (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(consumer_storage_inserted[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer: exchange: lost cookies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(producer_exchange_lost_cookies[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer: cookie channel length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "consumer_cookie_channel_length", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Consumer: batches in progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "consumer_storage_batches_in_progress",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}